-- MySQL Script generated by MySQL Workbench
-- 07/10/14 19:24:22
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema cms_project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cms_project` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `cms_project` ;

-- -----------------------------------------------------
-- Table `cms_project`.`cms_users_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cms_project`.`cms_users_status` (
  `status_u_mnm` CHAR(1) NOT NULL,
  `status_u_descript` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`status_u_mnm`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cms_project`.`cms_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cms_project`.`cms_users` (
  `email` VARCHAR(50) NOT NULL COMMENT 'это пользователький почтовый ящик',
  `password` VARCHAR(45) NOT NULL,
  `name` VARCHAR(100) NULL,
  `birthday` DATE NULL,
  `phone` VARCHAR(30) NULL,
  `info` VARCHAR(255) NULL,
  `status` CHAR(1) NOT NULL,
  PRIMARY KEY (`email`),
  CONSTRAINT `fk_cms_users_cms_users_status`
    FOREIGN KEY (`status`)
    REFERENCES `cms_project`.`cms_users_status` (`status_u_mnm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_cms_users_cms_users_status_idx` ON `cms_project`.`cms_users` (`status` ASC);

CREATE INDEX `phone_index` ON `cms_project`.`cms_users` (`phone` ASC);

CREATE INDEX `name_index` ON `cms_project`.`cms_users` (`name` ASC);


-- -----------------------------------------------------
-- Table `cms_project`.`cms_pages_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cms_project`.`cms_pages_status` (
  `status_p_mnm` CHAR(1) NOT NULL,
  `status_p_descript` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`status_p_mnm`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cms_project`.`cms_pages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cms_project`.`cms_pages` (
  `page_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `keywords` VARCHAR(255) NULL,
  `content` TEXT NOT NULL,
  `url` VARCHAR(255) NOT NULL,
  `p_status` CHAR(1) NOT NULL,
  PRIMARY KEY (`page_id`),
  CONSTRAINT `fk_cms_pages_cms_pages_status1`
    FOREIGN KEY (`p_status`)
    REFERENCES `cms_project`.`cms_pages_status` (`status_p_mnm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_cms_pages_cms_pages_status1_idx` ON `cms_project`.`cms_pages` (`p_status` ASC);

CREATE INDEX `title_index` ON `cms_project`.`cms_pages` (`title` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `cms_project`.`cms_users_status`
-- -----------------------------------------------------
START TRANSACTION;
USE `cms_project`;
INSERT INTO `cms_project`.`cms_users_status` (`status_u_mnm`, `status_u_descript`) VALUES ('a', 'admin');
INSERT INTO `cms_project`.`cms_users_status` (`status_u_mnm`, `status_u_descript`) VALUES ('u', 'user');

COMMIT;

